package model;

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

    private Integer id;
    private int accountIdaccount;
    private int taxRate;
    private String title;
    private double netPrice;
    private double fullPrice;
    private String code;
    private InvoiceHasItem invoiceHasItem;

    public Item() {
        this.invoiceHasItem = new InvoiceHasItem();
        invoiceHasItem.setCount(1);
    }

    public Item(int accountIdaccount, int taxRate, String title, double netPrice, double fullPrice, String code) {
        this.accountIdaccount = accountIdaccount;
        this.taxRate = taxRate;
        this.title = title;
        this.netPrice = netPrice;
        this.fullPrice = fullPrice;
        this.code = code;
        this.invoiceHasItem = new InvoiceHasItem();
        invoiceHasItem.setCount(1);
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getAccountIdaccount() {
        return this.accountIdaccount;
    }

    public void setAccountIdaccount(int accountIdaccount) {
        this.accountIdaccount = accountIdaccount;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public InvoiceHasItem getInvoiceHasItem() {
        return invoiceHasItem;
    }

    public void setInvoiceHasItem(InvoiceHasItem invoiceHasItem) {
        this.invoiceHasItem = invoiceHasItem;
    }

    public int getTaxRate() {
        return taxRate;
    }

    public void setTaxRate(int taxRate) {
        this.fullPrice = netPrice + netPrice * (double)taxRate/100.00;
        this.netPrice= fullPrice / (100.00 + (double)taxRate) * 100;
        this.taxRate = taxRate;
    }

    public double getNetPrice() {
        return netPrice;
    }

    public void setNetPrice(double netPrice) {
        this.fullPrice = netPrice + netPrice * (double)taxRate/100.00;
        this.netPrice = netPrice;
    }

    public double getFullPrice() {
        return fullPrice;
    }

    public void setFullPrice(double fullPrice) {
        this.netPrice= fullPrice / (100.00 + (double)taxRate) * 100;
        this.fullPrice = fullPrice;
    }

}
