package model;
// Generated 31.8.2014 5:02:47 by Hibernate Tools 3.6.0



/**
 * Rate generated by hbm2java
 */
public class Rate  implements java.io.Serializable {


     private Integer id;
     private String title;
     private int value;

    public Rate() {
      }

    public Rate(String title, int value) {
       this.title = title;
       this.value = value;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }




}


